//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using InControl;
namespace SControls
{
	
	public class ShipActions : PlayerActionSet
	{
		public PlayerAction lookLeft;
		public PlayerAction lookRight;
		public PlayerAction lookUp;
		public PlayerAction lookDown;
		public PlayerAction Left;
		public PlayerAction Right;
		public PlayerAction Up;
		public PlayerAction Down;
		public PlayerAction tL;
		public PlayerAction tR;
		public PlayerAction bL;
		public PlayerAction bR;
		public PlayerTwoAxisAction aAxs;
		public PlayerTwoAxisAction mAxs;
		
		public ShipActions()
		{
			lookLeft = CreatePlayerAction( "look x+" );
			lookRight = CreatePlayerAction( "look x-" );
			lookUp = CreatePlayerAction( "look y+" );
			lookDown = CreatePlayerAction( "look y-" );
			aAxs = CreateTwoAxisPlayerAction(lookLeft,
			                          lookRight,
			                          lookDown, //lord, lookDown
			                          lookUp);

			Left = CreatePlayerAction( "move x+" );
			Right = CreatePlayerAction( "move x-" );
			Up = CreatePlayerAction( "move y+" );
			Down = CreatePlayerAction( "move y-" );
			mAxs = CreateTwoAxisPlayerAction(Left,
			                          Right,
			                          Down, //breckfast
			                          Up);
			bL = CreatePlayerAction ("Bumper Left");
			bR = CreatePlayerAction ("Bumper Right");
			tL = CreatePlayerAction ("Trigger Left");
			tR = CreatePlayerAction ("Trigger Right");
		}

	}
	
}

